
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# custom keymaps
for keymap in 'emacs' 'viins' 'vicmd'; 
do
    # Ctrl-A goes to the beginning of the line
    bindkey -M $keymap '^A' beginning-of-line
    # Ctrl-E goes to the end of the line
    bindkey -M $keymap '^E' end-of-line
    # Ctrl-K deletes from the cursor to the end of the line
    bindkey -M $keymap '^K' kill-line
    # [Ctrl-RightArrow] - move forward one word
    bindkey -M $keymap '^[[1;5C' forward-word
    # [Ctrl-LeftArrow] - move backward one word
    bindkey -M $keymap '^[[1;5D' backward-word
done

# aliases
alias pj='ps -ef | grep java | grep -v grep'
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias ds='cd ~/dev/dev-setup'
alias gco='git checkout'
alias gdd='git difftool develop --no-prompt'
alias gdm='git difftool master --no-prompt'
alias gdn='git difftool --no-prompt'
alias gddno='git difftool develop --name-only'
alias gdh1='git difftool HEAD~1 --no-prompt'
alias j8='jenv global 1.8'

# prepend a space to the beginning of all .java files modified int the most recent x commits
# This makes it easy to find files to reformat in IntelliJ
touchRecent() {git diff --name-only HEAD~$1 | grep java | xargs sed -i '' '1s;^; ;'}
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"
